version: "3.8"
services:
  app:
    build:
      context: .
      target: deno
    container_name: discord-bot-app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=local
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
    tty: true
    command:
      - ash
      # - -c
      # - |
      # deno task watch
